# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
  appDir: p2-angular

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'ci'
    workingDir: '$(appDir)'
  displayName: npm ci

- script: npx ng build --prod
  workingDirectory: $(appDir)
  displayName: npx ng build


- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure Subscription 1(6fc81904-8f97-4b6e-917d-519941174623)'
    appType: 'webApp'
    WebAppName: 'AngularP2'
    packageForLinux: '$(appDir)/dist/*'
  displayName: deploy to azure web service
